### ISSUE TITLE
Connections counter

### ISSUE THREAD

**Issue by orrans** [felladrin/linkedin-autoconnect-chrome-extension#10]
Can you please add connection counter?
that it will show how many connections its asked after each request.
also maybe to add some option to tell it how much connection you want so if you configure it to 30 it will only press on 30 connections request and stop

**Comment by frazras** [comment]
I agree with this one, LinkedIn triggers its bot detection after about 100 connects. It would be nice to be able to count the connects in the current session and stop after a specified number.

**Comment by felladrin** [comment]
Good point. I'll add it to the roadmap.
