### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by zetaworks** [felladrin/linkedin-autoconnect-chrome-extension#11]
I think is not actually working? I tried to select all the recommended contacts but it just scrolll the page down but it doesn't select the contacts.

**Comment by felladrin** [comment]
If you scroll up and see some "Connect" buttons replaced by "Pending", it means it's working:
![image](https://user-images.githubusercontent.com/418083/97816336-3cc63d00-1c9d-11eb-9fdd-5ea9f4ace7ec.png)

That's the same result as if you were clicking them manually.
Can you please confirm if it's behaving correctly for you?

**Comment by zetaworks** [comment]
![image](https://user-images.githubusercontent.com/67185209/97865020-d0cdee00-1d09-11eb-93d7-c37825e35a50.png)

i can't see it

**Comment by felladrin** [comment]
Should be fixed now. The problem was that the extension was relying on English words to find buttons. As you were using a different language on LinkedIn, it was failing to find them.

Please, let me know if it's now working properly.
