### ISSUE TITLE
Latest version just go to bottom if page and go next

### ISSUE THREAD

**Issue by orrans** [felladrin/linkedin-autoconnect-chrome-extension#15]
Latest version just go to bottom if page and go next without press on the connection buttons
using version v1.2.7

**Comment by orrans** [comment]
Error:
Stack Trace
popup/popup.html:0 (anonymous function)

**Comment by 010101** [comment]
+1

**Comment by felladrin** [comment]
Thanks for letting me know.
It should be fixed now on [latest release](https://github.com/felladrin/linkedin-autoconnect-chrome-extension/releases/latest).
