### ISSUE TITLE
Feature Request: Extra options

### ISSUE THREAD

**Issue by TareqAbAmawi** [felladrin/linkedin-autoconnect-chrome-extension#165]
### Is your feature request related to a problem? Please describe.

NO

### Describe the solution you'd like

**Really great working and stable performance of the tool

The following options can be added:
1 - Stop the tool as soon as the message that the maximum number of connections requests has been reached appears.

2- Add a possibility option
-Add note-
With every connection request, this indicates that the person wants to know about himself and a reason for accepting the request.
“Very important and will make a difference.”

Thanks again.**

**Comment by DopaminingX** [comment]
Is your feature request related to a problem? Please describe.
NO

Describe the solution you'd like
**Have the Option to focus only on Connect, and skip Follow

The following options can be added:
1 - Skip people with the "Follow" button and only Connect to those with the Connect Option available, so we do not follow a bunch of unknown people :)

Thanks again.**
