### ISSUE TITLE
Dont go to the top of the page

### ISSUE THREAD

**Issue by orrans** [felladrin/linkedin-autoconnect-chrome-extension#25]
Version - 2.0.0 (latest)
after few pages its seems its not going to the top of the page and than its get stuck

configure to reproduce
63 connection for the session
went into someone specific connection page (to connect all HIS connections)
after 4 pages its stop to go to the top of the pages and just got stuck

**Comment by felladrin** [comment]
Fixed by https://github.com/felladrin/linkedin-autoconnect-chrome-extension/commit/48c38e76d73cfcc49ca0263e19854c474dd5ccf1 and available in [LinkedIn AutoConnect v2.0.1](https://github.com/felladrin/linkedin-autoconnect-chrome-extension/releases/tag/v2.0.1).
