### ISSUE TITLE
Number of connection per session not working

### ISSUE THREAD

**Issue by orrans** [felladrin/linkedin-autoconnect-chrome-extension#26]
Tried to test the number of connection per session and its not working
tried to enter 2 and then start the connecting but it continued even after 2 connections

**Comment by felladrin** [comment]
Thanks for reporting. Can you confirm if when it reached "2" it displaying the circle filled with green?

For example, when I tested it here, it reached "2", and then the button transited from "Stop Connecting" to "Start Connecting", indicating that it has been automatically stopped.

![image](https://user-images.githubusercontent.com/418083/121954487-77ca3c00-cd67-11eb-955d-9d3e0135a621.png)

Here is the URL I tested on: https://www.linkedin.com/search/results/people/?keywords=javascript%20developer&network=%5B%22S%22%5D&origin=FACETED_SEARCH

If the circle was not fully green, it's a sign that the extension options are not being saved.

**Comment by orrans** [comment]
Well i got it green but probably something was stuck or needed to refresh the page or something
working now, you can close it, thanks

**Comment by felladrin** [comment]
Alright, if it happens again, let me know. Maybe there is some edge case.
