### ISSUE TITLE
Erroneous behaviour [Chrome Jun17]

### ISSUE THREAD

**Issue by davidalbertonogueira** [felladrin/linkedin-autoconnect-chrome-extension#3]
Is it working? 
Didn't manage to work. It didn't send connection requests and started opening multiple empty messages in the bottom of the page.

**Comment by felladrin** [comment]
Hey there! Thanks for reporting. I haven't used it for some time. Maybe they've changed the page structure since then. I'll check it out and give you a feedback.

**Comment by davidalbertonogueira** [comment]
Any feedback?

**Comment by felladrin** [comment]
Fixed on 407d99cbcc36519f0d71bc5bbf63d24ccc681773.
I've also added instructions for manual installation on the Readme.
