### ISSUE TITLE
CORE FEATURE: The Connect Feature not working.

### ISSUE THREAD

**Issue by NitkarshChourasia** [felladrin/linkedin-autoconnect-chrome-extension#652]
### Bug description

The core feature of connecting is not working.
![image](https://github.com/user-attachments/assets/cfaea285-2cb6-4be7-8f5d-94efae380bb2)

### Steps to reproduce

Just follow people and it won't work.
The core function of the app is not working.
The follow button is not working at all.
**IT JUST SKIPS TO THE NEXT PAGE BY PAGINATION BUT DOESN'T FOLLOW ANYONE. **

### Expected behavior

It should follow people.
It should not only paginate to the next page.
It was working 8 Days ago.
Now, it is not working.

### Device info

Windows 10 Pro, Microsoft Edge, Google Chrome.
From three weeks I was using it on Microsoft Edge. It was working fine.
But now it is not working at all.

![image](https://github.com/user-attachments/assets/1999be11-b278-4ce1-92c7-9a54faf61742)

### Additional context

Tried with many different browsers but it is not working.
Thank you.

**Comment by NitkarshChourasia** [comment]
# EVEN TRIED ON DIFFERENT BROWSERS LIKE **MICROSOFT EDGE, GOOGLE CHROME, FIREFOX** 
# ALSO, ON DIFFERENT OPERATING SYSTEMS LIKE WINDOWS 10 PRO AND WINDOWS 11 PRO

## STILL IT WAS NOT WORKING.
PLEASE LOOK INTO IT.
THANK YOU.

**Comment by NitkarshChourasia** [comment]
@felladrin @schneems @NitkarshChourasia

**Comment by NitkarshChourasia** [comment]
@schneems @felladrin @schneems @felladrin

**Comment by NitkarshChourasia** [comment]
@schneems @schneems @felladrin @felladrin

**Comment by NitkarshChourasia** [comment]
@schneems @felladrin

**Comment by NitkarshChourasia** [comment]
@schneems @felladrin

**Comment by NitkarshChourasia** [comment]
@schneems @felladrin

**Comment by NitkarshChourasia** [comment]
@felladrin Why you closed it?
It is not working.

**Comment by felladrin** [comment]
Hi! Thanks for reporting!
The issue was auto-closed by GitHub, when I pushed the fix.
I was still releasing it the new version: v2.1.1
It's now released, so you can follow again the instructions on the Readme, to download the newest version, and it should now be clicking the Connect buttons properly, both on the Search page and My Network page.
