### ISSUE TITLE
CORE FEATURE: The Connect Feature not working.

### ISSUE THREAD

**Issue by NitkarshChourasia** [felladrin/linkedin-autoconnect-chrome-extension#653]
### Bug description

The core feature of connecting is not working.
![image](https://github.com/user-attachments/assets/38765ac9-772e-43e5-9aae-b5a1f6b70d7a)

### Steps to reproduce

Just follow people and it won't work.
The core function of the app is not working.
The follow button is not working at all.
**IT JUST SKIPS TO THE NEXT PAGE BY PAGINATION BUT DOESN'T FOLLOW ANYONE. **

### Expected behavior

It should follow people.
It should not only paginate to the next page.
It was working 8 Days ago.
Now, it is not working.

### Device info

Windows 10 Pro, Microsoft Edge, Google Chrome.
From three weeks I was using it on Microsoft Edge. It was working fine.
But now it is not working at all.
![image](https://github.com/user-attachments/assets/19333d6a-56bb-40b1-af11-1e6ebbccb09b)

### Additional context

Tried with many different browsers but it is not working.
Thank you.

**Comment by felladrin** [comment]
Hi! Thanks for reporting!
It's now fixed and released in v2.1.1
Could you please download the newest version (following the same instructions in the Readme) and confirm?

**Comment by NitkarshChourasia** [comment]
![image](https://github.com/user-attachments/assets/f7fe0a17-f99f-4372-837d-b5f90ec13e27)


Tested it and it is working wonderfully.
Thanks.

**Comment by NitkarshChourasia** [comment]
Thank you very much @felladrin .
Tested it extensively.
