### ISSUE TITLE
not working completely just move from page to another 

### ISSUE THREAD

**Issue by TareqAbAmawi** [felladrin/linkedin-autoconnect-chrome-extension#657]
### Bug description

not working completely just move from page to another 

### Steps to reproduce

Just open website and start extension

### Device info

Vivaldi 7.0.3495.18 (Stable channel) (64-bit)

**Comment by felladrin** [comment]
Hi, @TareqAbAmawi. A new version was released yesterday (v.2.1.1), which had a fix for a similar issue. Could you confirm if that’s the version number that shows on the Browser’s Extension Manager?

**Comment by TareqAbAmawi** [comment]
![2024-11-27 09_00_40-Extensions - Vivaldi](https://github.com/user-attachments/assets/93fca6d8-a5c6-4735-851d-bbfb952950c0)

**Comment by DereC4** [comment]
Upon clicking "start connecting" the extension simply skips to the next page, and so on, without doing any connections.

**Comment by felladrin** [comment]
Thank you both for confirming the problem. I'll look into it tonight.

Please let me also know which language are your browser in, because there's a low chance that the language could be affecting it. Because if you're not using it in English, I'll emulate the browser in a different language while looking for the fix.

**Comment by felladrin** [comment]
Found the issue and deployed v2.1.2 with the fix!

<img width="421" alt="image" src="https://github.com/user-attachments/assets/e7766a3b-c763-409d-b180-b03fe9c977ca">

Please download the new version following the installation instructions on Readme.

**Comment by DereC4** [comment]
was cramming for exams but ty for ur work
