### ISSUE TITLE
New problem : extension click on message also so when show premium message that stop send request 

### ISSUE THREAD

**Issue by TareqAbAmawi** [felladrin/linkedin-autoconnect-chrome-extension#663]
### Bug description

New problem : extension click on message also so when show premium message that stop send request 

### Steps to reproduce

Open Website
extension click on message also so when show premium message that stop send request 

https://github.com/user-attachments/assets/7a506e58-f547-433e-bc6e-33e9d6842b02

**Comment by NitkarshChourasia** [comment]
@felladrin Yes.
It is not working as expected.
Same happened with me, also.

**Comment by NitkarshChourasia** [comment]
![image](https://github.com/user-attachments/assets/23adfdc5-7b84-4f58-9e0c-8faccbdd674e)
EVEN WHEN DONE WITH PREMIUM LINKEDIN ACCOUNT.
Like I enabled 30-day free trial of LinkedIn premium still gave the same error.
Which slows down the pc **a lot** .

**Comment by NitkarshChourasia** [comment]
![image](https://github.com/user-attachments/assets/23adfdc5-7b84-4f58-9e0c-8faccbdd674e)
EVEN WHEN DONE WITH PREMIUM LINKEDIN ACCOUNT.
Like I enabled 30 day free trial of LinkedIn premium still gave the same error.
Which slows down the pc **a lot** .

**Comment by TareqAbAmawi** [comment]
yes still problem !

**Comment by NitkarshChourasia** [comment]
@felladrin Yes still the problem persists!

**Comment by NitkarshChourasia** [comment]
@felladrin When can we expect the bug to be solved?

**Comment by felladrin** [comment]
Thank you for the detailed report! I'll look into it at maximum tomorrow.

**Comment by DereC4** [comment]
To elaborate on this, it looks like your function goes down the list of buttons but it also clicks ones from people you can't connect with (private accounts, 3rd connections, etc) that will instead have a "Message" and not a "Connect".

Can probably just account for this by checking for the text in the button 

Other than that the thing works fine, ty for your work.

**Comment by felladrin** [comment]
Alright, it's finally fixed!
Please download the new version (v2.1.3) and let me know if there's any other misbehavior.

**Comment by TareqAbAmawi** [comment]
still not working 2.1.3

**Comment by felladrin** [comment]
It should close the "send premium message" and continue with the connections. Isn't it working like that?

Please also confirm if you clicked the button to reload the extension, in Chrome's Extensions Manager. Because sometimes it uses the extension files from cache.

**Comment by DereC4** [comment]
oop i haven't had the moment to test the new upadte but i will when i have time; either way, the current one with this bug works fine actually
