### ISSUE TITLE
Latest version cannot be load into chrome

### ISSUE THREAD

**Issue by orrans** [felladrin/linkedin-autoconnect-chrome-extension#8]
after unzip you cant load it to chrome

**Comment by felladrin** [comment]
Hi, the extension is being correctly loaded as described on the Readme: https://github.com/felladrin/linkedin-autoconnect-chrome-extension#install

Besides that, I've released a new version today. Please try it and let me know if it's working: https://github.com/felladrin/linkedin-autoconnect-chrome-extension/releases/latest
