### ISSUE TITLE
18.10 Plugin stopped working 

### ISSUE THREAD

**Issue by matandobr** [felladrin/linkedin-autoconnect-chrome-extension#9]
Hey!
Thank you for the great plugin, very useful. 
It seems like it stopped working nowadays, any ideas? 
(No connections are being sent)

**Comment by felladrin** [comment]
Hi, I've released a new version with the fix.
Please try it and let me know if it's working: https://github.com/felladrin/linkedin-autoconnect-chrome-extension/releases/latest

**Comment by matandobr** [comment]
Works great thank you!
They did added a few anti-bot features in the last update so I did get a "Running Out of Invitations to Connect" message and I'm restricted to send more invites for the moment, maybe there should be a longer timeout? anyways it works now thank you :)

**Comment by felladrin** [comment]
Thanks for the feedback!
Yeah, unfortunately, they have this limit, and I guess they have both hourly and daily limits. But I don't have the exact info and can't confidently increase the timeout.
If you happen to discover a better delay between clicks, please let me know! The current one is set to 1500ms [here](https://github.com/felladrin/linkedin-autoconnect-chrome-extension/blob/master/src/tab.js#L43).
